apiVersion: v1
kind: Service
metadata:
  name: pappers-api-service
spec:
  type: NodePort
  selector:
    app: pappers-api-app
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30110
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pappers-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pappers-api-app
  template:
    metadata:
      labels:
        app: pappers-api-app
    spec:
      containers:
        - name: pappers-container
          image: rogerranium/pappers
          imagePullPolicy: Never
          ports:
            - containerPort: 8080